Revert "build: update GrantBirki/git-diff-action to 3.0.0"
This reverts commit e4c52b2a6c89ac49aa9374f41efa9f0523f1b9ee.

🏃 starting the git-diff-action
Error: error getting git diff: Error: Command failed: git --no-pager diff --no-color --full-index  -- manifests/
fatal: bad revision ''